// LIST_ARTICLES
//LOAD
export const LIST_ARTICLES_LOAD       = 'LIST_ARTICLES_LOAD';
export const LIST_ARTICLES_SUCCESS    = 'LIST_ARTICLES_SUCCESS';
export const LIST_ARTICLES_ERROR      = 'LIST_ARTICLES_ERROR';
export const ARTICLE_SELECTED_LOAD    = 'ARTICLE_SELECTED_LOAD';
export const ARTICLE_SELECTED_SUCESS  = 'ARTICLE_SELECTED_SUCESS';
export const ARTICLE_SELECTED_ERROR   = 'ARTICLE_SELECTED_ERROR';
