// LIST_ARTICLES
//LOAD
export const LOAD_LIST_ARTICLES_INIT = 'LOAD_LIST_ARTICLES_INIT';
export const LOAD_LIST_ARTICLES_SUCCESS = 'LOAD_LIST_ARTICLES_SUCCESS';
export const LOAD_LIST_ARTICLES_FAILURE = 'LOAD_LIST_ARTICLES_FAILURE';
